remotechest:
  # Quantidade maxima de baus remotos por jogador
  quantidadePorJogador: 10
  # Ilimitado para Jogadores OP (sim/nao)
  ilimitadoParaOps: nao
  # Ilimitado para jogadores com as seguinte permissões (se não for para ninguem deixe [])
  # Exemplo:
  # ilimitadoParaPermissoes: []
  ilimitadoParaPermissoes:
  - remotechest.unlimited

  mensagens:
    definiuBau: '&6Voce definiu um bau! ($baus/$maximo)'
    execedeuLimite: '&6Voce excedeu o limite de baus!'
    removeuBau: '&6Voce removeu um bau! ($baus/$maximo)'
    removerBau: '&6Clique com o botado esquerdo em um dos baus para remove-lo!'
    naoPodeDefinir: '&6Voce nao pode definir este bau, tem certeza que ele é seu?'
    bauNaoEncontrado: '&6Bau nao encontrado, pode ter sido removido ou quebrado!'
